### ISSUE TITLE
Printer shuts down immediately

### ISSUE THREAD

**Issue by MrMilk23** [tinntbg/auto-power-off-klipper#1]
Hello

First of all I would like to thank you.
I have been looking for exactly such a macro.
My printer should only switch off after a certain temperature has been reached.

Unfortunately this does not work for me.
For example, if I start a print and click on the button, my printer immediately goes off within a few seconds.

Can you tell me what is wrong?

I added this to the end GCode in Prusaslicer.
UPDATE_DELAYED_GCODE ID=POWER_OFF_PRINTER_CHECK DURATION=30

**Comment by MrMilk23** [comment]
Config:
https://pastebin.com/Ff15vAS0

**Comment by tinntbg** [comment]
Hi @MrMilk23,
Can you please let me know on which button are you clicking? This functionality doesn't require any buttons to be clicked. 
Thanks,
TinnT

**Comment by MrMilk23** [comment]
Hello
please excuse the late reply!
Everything is working fine.
I had expected that I can decide for each print itself whether the printer shuts down.

Do you have any ideas on how to implement this?

**Comment by tinntbg** [comment]
Hi @MrMilk23, 

The script stops the execution if you start a new print or if you start heating your printer, this is one option to control this. 

The other option is to have 2 different version of the end gcode in your slicer. One for when you want to slice the file with the script been activated and the other with it. 

Thanks,
TinnT

**Comment by tinntbg** [comment]
Hi @MrMilk23, 

Is there anything else that I can help with on this issue or I can close it? 

Thanks,
TinnT
