### ISSUE TITLE
Add switch

### ISSUE THREAD

**Issue by AntoszHUN** [tinntbg/auto-power-off-klipper#2]
Is it possible to insert a switch so that it can be activated or deactivated during printing? So I mean, don't mess with pasting the gcode. So I'm going to start a 10 hour print. It takes 7 hours. Meanwhile, I have to leave home unexpectedly. Therefore, I would turn on the automatic shutdown with a button. Can it be fixed?

**Comment by tinntbg** [comment]
I have added 3 macros in order to make this working. Let me know if this works for you.
