### ISSUE TITLE
Auto shutdown klipper host when all printers finishes their jobs

### ISSUE THREAD

**Issue by lucasavendano** [tinntbg/auto-power-off-klipper#3]
Hi, thanks to you now I can power off my printer when print finishes.

But, could you help me with something else?

I have klipper installed on an old PC running linux, some kind of home made server, with 3 instances running (3 printers) and as it is not a raspberry I want to shut it down when all printers finishes their jobs, but I don't know how. I have been searching but seems it is  not a common thing so I couldn't find it.

Can you give me a hand with this?

Thanks!

**Comment by tinntbg** [comment]
Hi @lucasavendano , 

I'm not sure how you would be able to check if all printers have finished, but you can turn off the host with the following gcode: 
`gcode: {action_call_remote_method("shutdown_machine")}`

An option could be: 

If you have a home assistant you can integrate all 3 klipper instances in klipper (I can assist you with this) and have an automation in home assistant that triggers a shut down of the host on the last printer. You can use moonraker api to do that: https://moonraker.readthedocs.io/en/latest/web_api/

Please let me know if I can help with something else. 

Thanks,
TinnT

**Comment by lucasavendano** [comment]
thanks for your answer!

> check if all printers have finished

check if all printers have finished is what i can´t find, and if i knew how i think don´t mind where to place de check, i will keep searching for something that point me in the right direction.

I don´t have an assistant but may be could do something with an d1 mini that i have there, but its a little far for me right now😁

thanks!!

**Comment by tinntbg** [comment]
Hi @lucasavendano ,

I did some digging into this and I found another option that you can try.

You can use KIAUH to install gcode_shell_command - https://github.com/th33xitus/kiauh and then use the following logic:
 
Create a macro that runs on your printer ends macro that runs a SH script, example:
`[gcode_shell_command pushover_notify]
command: sh /home/pi/klipper/scripts/pushover.sh
timeout: 10.
verbose: True`

In the script you can use curl to get the status of your other klipper instance using the moonraker API: https://moonraker.readthedocs.io/en/latest/web_api/

If any of your printers are printing you can exit the script, if not you can periodically check the API and see the toolhead and bed temperature. Once they are below a set degrees, you can shutdown the printer and the host. 

I hope that this helps, 

Thanks,
TinnT

**Comment by lucasavendano** [comment]
Hi @tinntbg , thank you for spend time investigating options. I´ll check the moonraker API, i´ve been thinking i don´t always want to shutdown the host, only when i see that a print job will end at midnight or something like that, so maybe could be a simple macro launched manually on the instance that will finish last, and thats all.

Thanks!
Lucas
